language: node_js
dist: trusty
sudo: required
node_js: stable
install:
  - npm i
  - bower i
script:
  - npm run build
  - npm run example-map
  - npm run example-map-halogen
  - npm run example-heatmap-halogen
  - npm run example-signal-halogen
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: example/signal-halogen/dist
  on:
    branch: master
